
## SYSTEM OPTIONS
export TF_BASH=bash
#export TF_BASH=sbatch

export THREADS=32

## SCRATCH STORAGE DIRECTORY
export STORAGE_DIR=/home/vantwisk/vantwisk/fusions/seq_run
[ ! -d ${STORAGE_DIR} ] && mkdir ${STORAGE_DIR}

## BASE STORAGE DIRECTORIES
export REF_STORAGE_DIR=${STORAGE_DIR}/ref
[ ! -d ${REF_STORAGE_DIR} ] && mkdir ${REF_STORAGE_DIR}
export SIM_STORAGE_DIR=${STORAGE_DIR}/sim
[ ! -d ${SIM_STORAGE_DIR} ] && mkdir ${SIM_STORAGE_DIR}
export RESULTS_STORAGE_DIR=${STORAGE_DIR}/results
[ ! -d ${RESULTS_STORAGE_DIR} ] && mkdir ${RESULTS_STORAGE_DIR}

## ALIGNMENT STORAGE DIRECTORY
export ALIGNMENT_STORAGE_DIR=${STORAGE_DIR}/alignments
[ ! -d ${ALIGNMENT_STORAGE_DIR} ] && mkdir ${ALIGNMENT_STORAGE_DIR}

## RESULTS STORAGE DIRECTORIES
export JAFFAL_STORAGE_DIR=${RESULTS_STORAGE_DIR}/jaffal
[ ! -d ${JAFFAL_STORAGE_DIR} ] && mkdir ${JAFFAL_STORAGE_DIR}
export LONGGF_STORAGE_DIR=${RESULTS_STORAGE_DIR}/longgf
[ ! -d ${LONGGF_STORAGE_DIR} ] && mkdir ${LONGGF_STORAGE_DIR}
export GENION_STORAGE_DIR=${RESULTS_STORAGE_DIR}/genion
[ ! -d ${GENION_STORAGE_DIR} ] && mkdir ${GENION_STORAGE_DIR}
export PBFUSION_STORAGE_DIR=${RESULTS_STORAGE_DIR}/pbfusion
[ ! -d ${PBFUSION_STORAGE_DIR} ] && mkdir ${PBFUSION_STORAGE_DIR}
export FUSIONSEEKER_STORAGE_DIR=${RESULTS_STORAGE_DIR}/fusionseeker
[ ! -d ${FUSIONSEEKER_STORAGE_DIR} ] && mkdir ${FUSIONSEEKER_STORAGE_DIR}

export ARRIBA_STORAGE_DIR=${RESULTS_STORAGE_DIR}/arriba
[ ! -d ${ARRIBA_STORAGE_DIR} ] && mkdir ${ARRIBA_STORAGE_DIR}
export STARFUSION_STORAGE_DIR=${RESULTS_STORAGE_DIR}/starfusion
[ ! -d ${STARFUSION_STORAGE_DIR} ] && mkdir ${STARFUSION_STORAGE_DIR}

## GRAPH STORAGE DIRECTORIES
export GRAPHS_STORAGE_DIR=${RESULTS_STORAGE_DIR}/graphs
[ ! -d ${GRAPHS_STORAGE_DIR} ] && mkdir ${GRAPHS_STORAGE_DIR}

## RESOURCES
export DNA_REFERENCE=${REF_STORAGE_DIR}/Homo_sapiens.GRCh38.dna.primary_assembly.fa
export CDNA_REFERENCE=${REF_STORAGE_DIR}/Homo_sapiens.GRCh38.cdna.all.fa
export GTF_REFERENCE=${REF_STORAGE_DIR}/Homo_sapiens.GRCh38.105.gtf

export PBMM2_MMI=${REF_STORAGE_DIR}/hg38_gencode.mmi

export STAR_INDEX=${REF_STORAGE_DIR}/hg38_star_index

export GENOMIC_SUPER_DUPS=${REF_STORAGE_DIR}/genomicSuperDups.txt

## Annotion Limit Settings
export TRANSCRIPT_LIMIT=1000
export TRANSCRIPT_LIMITED_FILE=${REF_STORAGE_DIR}/Homo_sapiens.GRCh38.cdna.limited_${TRANSCRIPT_LIMIT}.fa

## FUSION SIMULATION SETTINGS
export NFUSIONS=100
export FUSIM_FASTA_FILE=${REF_STORAGE_DIR}/fusim_${NFUSIONS}.fasta
export FUSIM_TXT_FILE=${REF_STORAGE_DIR}/fusim_${NFUSIONS}.fxt
export FUSION_TRANSCRIPTOME=${REF_STORAGE_DIR}/Homo_sapiens.GRCh38.cdna.limited_${TRANSCRIPT_LIMIT}_fusions_${NFUSIONS}.fa

## LONGREAD AND SHORTREAD READ SIMULATION SETTINGS
export N_TRANSCRIPTS=('1') #('1' '2' '4' '8' '16')
export REPLICATES=1 #10
export COVERAGE=(10) #(3 5 10 30 50 100)
export QUALITY=('95,100,4')  #('75,90,8' '87,97,5'  '95,100,4')
export TECH=('pacbio2016' 'nanopore2020')
export READ_LENGTHS=(100 150)

## LONGGF OPTIONS
export MIN_OVERLAP_LEN=100
export BIN_SIZE=50
export MIN_MAP_LENGTH=100

## JAFFAL OPTIONS

## GENION OPTIONS
export GENION_MIN_SUPPORT=2

## PBFUSION OPTIONS
export PBFUSION_MIN_COVERAGE=2

$ART_P
$RUSTYREAD_P
$MINIMAP2_P
$SAMTOOLS_P
$JAFFA_P
$GENION_P
$PBFUSION_P
$STAR_P
$STAR_FUSION_P
$ARRIBA_P
